import { StrictMode, lazy, Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import App from './App.tsx';
import ErrorBoundary from './components/ErrorBoundary.tsx';
import './index.css';

// Register the Workbox service worker generated by vite-plugin-pwa.
// This enables PWA installability and offline asset caching.
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // SW registration is best-effort — silently skip on HTTP or restricted environments.
    });
  });
}

// Lazy-load secondary pages — they're not needed on first paint and
// together make up ~15-20% of the bundle. Suspense fallback is a blank
// page in the brand background colour so the flash is seamless.
const Privacy  = lazy(() => import('./pages/Privacy.tsx'));
const Terms    = lazy(() => import('./pages/Terms.tsx'));
const Account  = lazy(() => import('./pages/Account.tsx'));
const NotFound = lazy(() => import('./pages/NotFound.tsx'));

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ErrorBoundary>
      <BrowserRouter>
        <Suspense fallback={<div className="min-h-screen bg-[#F5F5F0]" />}>
          <Routes>
            <Route path="/" element={<App />} />
            <Route path="/privacy" element={<Privacy />} />
            <Route path="/terms" element={<Terms />} />
            <Route path="/account" element={<Account />} />
            <Route path="*" element={<NotFound />} />
          </Routes>
        </Suspense>
      </BrowserRouter>
    </ErrorBoundary>
  </StrictMode>,
);
